nerdhaus/blog/models.py
# -*- coding: utf-8 -*-

from sqlalchemy import Column
from ..extensions import db
from ..utils import STRING_LEN

class Post(db.Model):
    id          = Column(db.Integer, primary_key=True)
    title       = Column(db.String(STRING_LEN))
    content     = Column(db.String(STRING_LEN))
    published   = Column(db.Date)
    author_id   = Column(db.Integer, db.ForeignKey('user.id'))

class Author(db.Model):
    id          = Column(db.Integer, primary_key=True)
    email       = Column(db.String(128), unique=True)
    name        = Column(db.String(128))

nerdhaus/blog/forms.py
# -*- coding: utf-8 -*-

from flask.ext.wtf import (Form, TextField, TextAreaField, SubmitField,
        Required, Email)
from flask.ext.wtf.html5 import EmailField

class PostForm(Form):
    title           = TextField(u'Post Title', [Required()])
    content         = TextAreaField(u'Content', [Required()])
    author_email    = TextField(u'Author\'s Email', [Required(), Email()])
    submit          = SubmitField(u'Submit')

nerdhaus/__init__.py
from app import create_app

nerdhaus/app.py
from flask import Flask, render_template
from .frontend import frontend
from .blog import blog
from .extensions import login_manager
import random

BLUEPRINTS = [blog, frontend]

def create_app(app_name=__name__, config=None, blueprints=[]):
    app = Flask(app_name)
    configure_app(app, config)

    if not blueprints:
        blueprints = BLUEPRINTS

    bootstrap_blueprints(app, blueprints)
    register_extensions(app)
    return app

def bootstrap_blueprints(app, blueprints):
    for bp in blueprints:
        app.register_blueprint(bp)

def configure_app(app, config):
    app.secret_key = 'a;lskfdjaio;enfas;lknev;soi8evnse'
    app.config.from_object(__name__)
    app.config.from_pyfile('settings.cfg')

def register_extensions(app):
    login_manager.init_app(app)

    @app.errorhandler(404)
    def not_found(error):
        gifs = [
        'gangnamvator.gif',
        'hammer_duo.gif',
        'Hammertime.gif',
        'mc_hammer.gif',
        'Mc Hammer Zidane Trick-329529.gif',
        'Only_6c1fbe_419666.jpg',
        'pancake_dj.gif',
        ]

        gif = random.choice(gifs)
        return render_template('errors/404.html', gif=gif)

nerdhaus/blog/__init__.py
# -*- coding: utf-8 -*-

from .views import blog
from .models import Post

nerdhaus/blog/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, abort, request, flash
from flask.ext.login import login_required, current_user

from ..extensions import db
from models import Post, Author
from forms import PostForm


def admin_required():
    pass

blog = Blueprint('blog', __name__, url_prefix='/blog')

@blog.route('/')
def index():
    posts = ['sweet jesus'] 
    return render_template('blog/index.html', posts=posts)

@blog.route('/post/<int:post_id>')
def post(post_id):
    return 'view one post'

@blog.route('/archive')
def archive():
    return 'view archive'

@blog.route('/admin')
@login_required
def admin():
    return 'access admin backend'

@blog.route('/admin/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(post_id):
    return 'edit that post'

@blog.route('/admin/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(post_id):
    return 'delete that post'

@blog.route('/admin/post/new', methods=['GET', 'POST'])
def new():
    form = PostForm()
    if form.validate_on_submit():
       post = Post() 
       post.author = Author()
       post.content = form.content.data
       post.title = form.title.data
       post.author.email = form.author_email.data
       db.session.add(post)
       db.session.commit()
       return redirect(url_for('blog.index'))

    return render_template('blog/new.html', form=form)

nerdhaus/frontend/__init__.py
from views import frontend

nerdhaus/frontend/views.py
from flask import Blueprint, render_template, abort

frontend = Blueprint('frontend', __name__)

@frontend.route('/', methods = ['GET'])
def index():
    return render_template('frontend/index.html')

@frontend.route('/blag/', methods=['GET'])
def blag_index():
    return render_template('blag/index.html')

@frontend.route('/shows/', methods=['GET'])
def shows_index():
    return render_template('shows/index.html')

@frontend.route('/portfolio/', methods=['GET','POST'])
def portfolio_index():
    return render_template('portfolio.html')

@frontend.route('/pages/<page>')
def show(page):
    try:
        return render_template('pages/%s.html' % page)
    except:
        abort(404)

nerdhaus/templates/blag/index.html
{% extends "layouts/layout.html" %}
{% block title %}Blag{% endblock %}
{% block you_are_here %}The Blag{% endblock %}
{% block body %}
<section class="blag">
    <article>
        <h3> Perspective <p class="date">7/30/2013</p></h3>
        <h4> by <a href="http://ebanis.tumblr.com/">CJ Summers </a></h4>
        <p>
        These days, it is remarkably easy to lose the details of what is
        happening, often because it is presented exclusively in regards to a
        single element of its context. We see the conflicts in various Middle
        Eastern and African nations being exclusively framed as Sectarian in
        nature, be it Sunni vs. Shiite or Secular vs. Islamist – rather than as
        a fraction of the larger picture, the fact that mundane things like food
        supplies and economics tend to have far more to do with political dissent and
        uprising than ideals. It is tempting to write this off as a
        critique of the providers of news, but that is not enough; we have to
        realize it is to some degree our fault as well. When we accept black and
        white arguments without question, we do ourselves a great disservice: We
        refuse to learn the greater context of the issue at hand. The truth of
        the matter is, we live in a world of greys. Nothing is clear cut, and
        every decision we or our political bodies make has varied consequences.
        Dismissing the news for being boring or depressing is your choice, but
        if you ignore events going on that affect you – and we are all affected
        by much of the news coming out in the States nowadays – where will you
        be when the opportunity comes around to do something about it? I can say
        with confidence that everyone has an opinion on issues like mass
        surveillance of Internet traffic. Everyone has an opinion when human
        lives are on the line, even distant ones. With that in mind, let's think
        for a moment about what America looks like from the outside.
        </p>

        <p>
        This country came out of a massive civil war some 150 years ago in rough shape,
        leading to some pretty major cultural divides but eventually regaining
        functionality. Since then, political power has primarily been shared between two
        parties, though they flip-flop over which is in charge every four years or so.
        Third parties are allowed and even manage some small victories in local
        elections, but any time one gets enough support to really put up a fight on the
        national level, the rules are changed and they are cast out again. So it is not
        surprising that despite televised debates and supposedly intense elections, the
        actual political makeup of America's ruling bodies has changed very little over
        time – the two powers are always nominatively at odds, but have a strange way of
        coming together over things that benefit their role as the ruling class –
        surveillance, funding allocations, regulations for election campaigns, that kind
        of thing.  
        </p>

        <p>
        Implicit in this farce is our big-budget media, backed by the same investors as
        most of the politicians mentioned above. Their role is not only to polarize the
        issues between the two factions but to spin the things they do manage to
        accomplish in a positive way: Getting rid of campaign donation restrictions
        benefits free speech, mass surveillance is necessary to prevent terrorism, etc.
        These organizations are not necessarily made of abhorrent people, but they are
        told what they can and can not say by business savvy sorts that are funded by
        the same people as the ruling class. This conflict of interest is immensely
        detrimental to journalism, because the world is so complicated that we need news
        aggregates to keep up with anything beyond the local level – and our perceptions
        are shaped based on the news we see, and increasingly the stories are framed by
        the ruling class of wealthy people. Look to the mainstream's coverage of the
        Occupy protests, or the Trayvon Martin case, as compared to the coverage offered
        by numerous independent outlets, for examples of how this can go wrong.  Even if
        we lack an actual state-owned media, such as Egypt's, it is the people in power
        calling the shots on everything we hear from it. Why would they ever report
        favorably on something that shows them to be in the wrong?
        </p>

        <p>
        So this is the situation the rest of the world sees: A superpower that
        claims the virtue of democracy, in which the main legislative body is
        dysfunctional (as indicated by the 2012 congress being one of the least
        productive in decades); a country where the executive arm of
        the government can wage war without the legislative body's and therefore
        peoples' consent, and in which the top leaders are all elected in large
        part based on the amount of money they can raise from largely corporate
        sponsors. If, as stated by noted expert on the subject Benito Mussolini,
        Fascism is a “Merger of state and corporate interests”, America has an
        absolutely brilliant setup for it to flourish, and they can even say it
        was the result of public choice. As a citizen of any part of the world
        you can only see America as a juggernaut of a country, with the biggest
        military the world has ever seen, already lashing out at countries like
        Iraq or Pakistan for reasons that benefit a network of defense industry
        partners far more than any American citizen.  Looking at America as an
        outsider leads to two thoughts; The first, “When will the nation's
        appetite for resources and wealth bring it to my shores?”, quickly
        followed by the second: “What can I do to stop it?”
        </p> 

        <p>
        This is the point at which the interests of those on the inside and those on the
        outside intersect. We as citizens must realize that this is to some degree our
        fault – We did not push, be it through direct action, legislation, or organized
        dissent, hard enough when we saw corruption in our country. We were complicit in
        not holding anyone accountable for the recent financial crisis, did not question
        the dirty wars started by our leaders without our or congress' consent, and did
        not care when innocent people in other countries died for, as it was argued, our
        safety. We are not entirely to blame for the executive power grabs made in
        recent years, but building resistance against further trespasses is on us.
        </p>

        <p>
        If you take anything from this, realize that apathy is not a sufficient answer
        to our problems. If we continue failing to oppose the direction our country is
        headed in, we will be complicit in the atrocities it commits. Politics is hard,
        following the news takes time, and discussing issues with friends can be
        divisive – but if we do not start paying attention to the issues at hand,
        questioning what we are told, and searching for our own answers, we will soon be
        citizens of the most powerful fascist nation the world has ever seen. Avoiding
        that is worth a few minutes reading of some news on the Internet every day,
        voting against the ruling parties, and showing nonviolent resistance where it
        can do good. What we write off as “just politics”, filing it as some kind of
        distraction, affects every citizen of the world. Is it not time to start paying
        attention?
        </p>
    </article>
</section>
{% endblock %}

nerdhaus/templates/blog/index.html
{% extends "layouts/layout.html" %}
{% block title %}Blog{% endblock %}
{% block you_are_here %} The Blog {% endblock %}
{% block body %}
<section class="blog">
    {% if posts %}
        {% for post in posts %}
            <article>
            {{ post }}
            </article>
        {% endfor %}
    {% endif %}
    <article>
        <h3> collapsible top nav <p class="date">7/30/2013</p></h3>
        <p> so as the site grows and develops, i'm implementing more and varied
            patterns for both the ui and the back end.  today, i did a little
            research and banged out a responsive nav menu for the header up there.
        </p>

        <p> (if you aren't sure what i'm talking about, drag the corner of your
            browser window around to resize the window and watch how things change.)
        </p>

        <p> i made use of a straightforward technique that principally does two
            things:
        </p>
        <ol>
            <li> sets a class of <span class="inline code">active</span> on the 
            <span class="inline code">&lt;ul&gt;</span>
                    when the  <span class="inline code">menu</span> anchor is
                    clicked.
            </li>
            <li> based on the presence of the <span class="inline
                code">active</span> class, styles the <span class="inline code"> 
                max-height</span> of the unordered list that contains the navigation 
                anchors.
            </li>
        </ol>

        <p> i use <a href="http://jquery.com">jQuery</a> manipulate the classes
        and css transitions to make the whole effect smoother and more pallatable. 
        </p>

        <p> here's my markup, first: </p>
            <pre class="code">
            &lt;nav class="mobile"&gt;
                &lt;ul id="#nav"&gt;
                    &lt;li&gt;&lt;a href="http://nerdha.us"&gt; Home &lt;/a&gt;&lt;/li&gt;
                    &lt;li&gt;&lt;a href="http://nerdha.us/blog"&gt; Blog &lt;/a&gt;&lt;/li&gt;
                    &lt;li&gt;&lt;a href="http://nerdha.us/blag"&gt; Blag &lt;/a&gt;&lt;/li&gt;
                    &lt;li&gt;&lt;a href="http://nerdha.us/shows"&gt; Shows &lt;/a&gt;&lt;/li&gt;
                &lt;/ul&gt;
                &lt;a class="nav-toggle" href="#nav"&gt; Menu &lt;/a&gt;
            &lt;/nav&gt;
            </pre>
        </p>

        <p> here's the javascript: </p>

        <pre class="code">
            $(document).ready(function () {
                $('a.nav-toggle').click(function () {
                    $('nav.mobile ul').toggleClass('active'); 
                });
            });
        </pre>

        <p> and the styles, processed with <a href="http://lesscss.org/">less</a>: </p>

        <pre class="code">
            nav.mobile {
                background: rgba(0, 0, 0, 0.9);
                overflow: hidden;
                
                a {
                    border-bottom: 1px solid #000;
                    color: @bg1;
                    display: block;
                    text-decoration: none;
                    padding: 5px 0 5px 2em;
                }

                ul { 
                    transition: max-height 0.4s ease-out 0s;
                    visibility: hidden;
                    max-height: 0;
                    padding: 0; 
                }

                a.nav-toggle {
                    float: right;
                    padding-right: 2em;
                }
            }

            nav.mobile ul.active {
                max-height: 143px;
                visibility: visible;
            }
        </pre>

        <p> i've snipped out the rules that don't pertain to creating the
        collapsible nav, so if you you want to get the exact same look and feel, i
        suggest you look at mah source :]
        </p>

        <p> in a nutshell, the javascript binds a click handler on the 'Menu' anchor
        that toggles a class on and off the unordered list that comprises the actual
        menu for the site.  when it's <span class="inline code">active</span>, the
        list smoothly expands to the <span class="inline code">max-height</span>
        thanks to that transition declaration.
        </p>

        <p> css transitions are a great way to put those extra finishing touches on
        a site's UX, but keep in mind that they are only supported in IE &gt;=
        version 10. for older versions, get you some <span class="inline code">
        jQuery.animate()</span>.
        </p>
    </article>
    <article>
        <header>
            <h3>on conversation</h3>
            <p class="date">7/16/2013</p>
        </header>
        
        <p> conversation is one of the most valuable resources that we engage on a daily 
        basis.  the act itself is valuable, regardless of the 
        outcome. debate, discussion, anything that transcends the simple exchange 
        of pleasantries and information (hi how are you i'm fine what can i get 
        a triple yeah you want two please six fifty thanks).</p>

        <p> even when you end up with a room (tangible <em>or</em> digital) full of 
        pissed off people.  there's a fine line, sure, because something must 
        actually have been said for that emotion to be worth a damn. but by that same 
        token:  if somebody's pissed, it's more often for a reason.  something
        was brought up that people think is worth getting pissed about. some thing
        worth a damn.
        </p>

        <p> this martin-zimmerman business matters. it makes us talk.  when we talk,
        we shape each others' opinions. we hash shit out.
        </p>

        <p> <a href="http://www.imdb.com/title/tt0375679/">Crash</a> is a good movie.  
        solid performances by talented people, a complicated but engaging yarn, and
        a meaningful shot at a potent, contemporary issue. but what really made that movie 
        magical to me was it's bordering-on-realistic (for two hours worth of movie, 
        anyway) examination of the simple causality that rules our lives.
        </p>

        <p> a word there, the flick of a pen, a simple conversation.  or a hard one.
        somebody's pissed, somebody goes home, somebody makes a phone call and your
        life is different. you can make it better, or you can make it worse.   
        </p>

        <p> people don't need to die. and when they do, it's worth making it a point 
        not to ignore it, to blow it off. talk about it. <em>at least</em> talk
        about it.
        </p>
    </article>

    <article>
        <header>
            <h3>the blog is open to contribution</h3>
            <p class="date">7/9/2013</p>
        </header>
    <p> so feel free to submit something.  email it to me at <a href="mailto:n.e.lorenson@gmail.com">n.e.lorenson@gmail.com</a> and put BLOG in the subject.  be sure to note whether or not you’d like to remain anonymous.
    </p>
    <p> as the site grows i'll be seperating the submissions from my personal blog and placing them on their own feed. </p>
    </article>
    <article>
        <header>
            <h3>this is your brain, organized</h3>
            <p class="date">7/7/2013</p>
        </header>

        <p> i don't know about you, but i am seriously scatterbrained. </p>
        <p> to be fair, i'm old school add, diagnosed in the early nineties (second grade, maybe?), and not just a spaz. </p>
        <p> regardless, the way my mind works has forced me to come up with ways of keeping my shit straight, and one of the most 
        powerful has been to write everything out.  principally, for me, this means writing todo lists and keeping a <a href="">wiki</a>.
        </p>
        <p> a simple todo list (i skip fancy tools here; an excel spreadsheet on google drive is way fancy enough) with columns for status,
        notes, and links anchors me to a set of things to pursue for a day.  it also provides a nice way to dump things out of my mental 
        space so that i can revisit them later.  forgetfulness is an artform that i've spent many years refining, so anything that helps 
        save brain cycles by remembering things for me is a huge boon. 
        </p>
        <p> now the wiki is my notebook, full of notes.  i use it take document, retain, and reference so many things that i learn, mainly 
        programming and business stuff. i take notes on things constantly.  read a good article on css best practices?  notes.  pick up and 
        start learning a new library?  takin' notes.  learn about a new pattern for solving a problem?  note time. 
        </p>
        <p> the more i do this, the more i fall in love with it.  it helps me track my learning arc through doing projects and picking up more
        of my craft.
        </p>
        <p> as an added bonus, i keep it public so my pain can be your gain.  this also encourages me to make it nice, real nice, so people
        will find it easy to digest and i'll never be bummed out using it.
        </p>
        <p> right now i use <a href="http://moinmo.in/">moinmoin</a>. i add to it constantly, mapping out what i know and use as i learn.
        </p>
    </article>
    <article>
        <header>
            <h3>stupid simple flask app</h3>
            <p class="date">7/6/2013</p>
        </header>
        
        <p>consider <a href="http://flask.pocoo.org">flask</a>, a delightful web application framework, commonly referred to as a micro framework.</p>
        <p>firing up a running web app in flask is cake.  import the Flask class, instantiate an application object from it, define a route and view function, and call <span class="inline code">run()</span> on your app object.</p>
        <pre class="code"><code>
        from flask import Flask, render_template

        app = Flask(__name__)

        @app.route('/')
        def index():
            return render_template('index.html')

        if __name__ == '__main__':
            app.run()
        </code></pre>
        <p>
            easy peasy.  this will serve the template called <span class="inline code">
                index.html</span> at the root ('<span class="inline code">/</span>') of the domain where the app is hanging out.
        </p>
    </article>
    <article>
        <header>
            <h3>fab fun times</h3>
            <p class="date">7/6/2013</p>
        </header>
        <p>so as i continue on my magical journey to production quality 
        <a href="http://flask.pocoo.org">flask</a>, i discover my deep desire 
        for a not dumb deployment solution.  hence, 
        <a href="http://docs.fabfile.org/en/1.6/">fabric</a>.</p>

        <p>working with fabric, after some intial hiccups,  is actually pretty 
        delightful. it's a library created to facilitate interaction with remote 
        systems via ssh.  it picks up your <span class="inline code">.ssh/config</span> 
        and uses it right out of the box, and comes equipped with a simple 
        vocabulary for moving around the filesystem and working with files.</p>

            <p>i intend to use this lib quite a bit, so more in depth accounts of my experience doing so will follow.</p>
    </article>
    <article>
        <header>
            <h3>hike night:  a hike at night</h3>
            <p class="date">7/5/2013</p>
        </header>
        <p> night one was a success.  i've reconsidered posting the route.  invite only.</p>
        <p> we found a delightful little creek with some absolutely quaint industrial rubble. i was enchanted by the host of spider webs.  walking a few yards up the creek,
        i found that i couldn't take three steps without almost creaming some little spiders pad.</p>
        <p> against established expectations,  clarksville has some nice little spots.  you just have to dig. </p>
    </article>
    <article>
        <header>
            <h3> night hike: the setup </h3>
            <p class="date">7/1/2013</p>
        </header>
        <p> this 4th of july we'll be engaging in the first night hike.  should be fun.  i'll post the route below.  for extra pop,  we'll be encouraging participants to bring along their favorite fireworks. 
        </p>
    </article>

    <article>
        <header>
            <h3> welcome to the hive mind,  nerdhaus central </h3>
            <p class="date">7/1/2013</p>
        </header>
        <p> a log of the activities of the haus.  see this domain for tech, culture, and a running commentary of our work and escapades.  
        </p>
        <p> also note that the blog is open for submissions.  </p>
    </article>
</section>
{% endblock %}

nerdhaus/templates/blog/new.html
{% from "macros/_form.html" import render_form %}
{% extends "layouts/layout.html" %}

{% block title %}Blog{% endblock %}

{% block body %}
    {{ render_form(url_for('blog.new'), form) }}
{% endblock %}

nerdhaus/templates/frontend/index.html
{% extends "layouts/layout.html" %}
{% block body %}
    <menu class="grid">
        <a class="" href="http://nerdha.us/blog"><h4>listen to me talk</h4><h1>BLOG</h1></a>
        <a class="" href="http://nerdha.us/blag"><h4>tell us how it is</h4><h1>BLAG</h1></a>
        <a class="" href="http://nerdha.us/shows"><h4>check out our</h4><h1>HAUS SHOWS</h1></a>
    </menu>
{% endblock %}

nerdhaus/templates/index.html
{% extends "layout.html" %}
{% block body %}
<article>
<h3>the blog is open to contribution<span class="date">7/9/2013</span></h3>
<p> so feel free to submit something.  email it to me at <a href="mailto:n.e.lorenson@gmail.com">n.e.lorenson@gmail.com</a> and put BLOG in the subject.  be sure to note whether or not you’d like to remain anonymous.
</p>
<p> as the site grows i'll be seperating the submissions from my personal blog and placing them on their own feed. </p>
</article>
<article>
    <h3>this is your brain, organized<span class="date">7/7/2013</span></h3>
    <p> i don't know about you, but i am seriously scatterbrained. </p>
    <p> to be fair, i'm old school add, diagnosed in the early nineties (second grade, maybe?), and not just a spaz. </p>
    <p> regardless, the way my mind works has forced me to come up with ways of keeping my shit straight, and one of the most 
    powerful has been to write everything out.  principally, for me, this means writing todo lists and keeping a <a href="">wiki</a>.
    </p>
    <p> a simple todo list (i skip fancy tools here; an excel spreadsheet on google drive is way fancy enough) with columns for status,
    notes, and links anchors me to a set of things to pursue for a day.  it also provides a nice way to dump things out of my mental 
    space so that i can revisit them later.  forgetfulness is an artform that i've spent many years refining, so anything that helps 
    save brain cycles by remembering things for me is a huge boon. 
    </p>
    <p> now the wiki is my notebook, full of notes.  i use it take document, retain, and reference so many things that i learn, mainly 
    programming and business stuff. i take notes on things constantly.  read a good article on css best practices?  notes.  pick up and 
    start learning a new library?  takin' notes.  learn about a new pattern for solving a problem?  note time. 
    </p>
    <p> the more i do this, the more i fall in love with it.  it helps me track my learning arc through doing projects and picking up more
    of my craft.
    </p>
    <p> as an added bonus, i keep it public so my pain can be your gain.  this also encourages me to make it nice, real nice, so people
    will find it easy to digest and i'll never be bummed out using it.
    </p>
    <p> right now i use <a href="http://moinmo.in/">moinmoin</a>. i add to it constantly, mapping out what i know and use as i learn.
    </p>
</article>
<article>
    <h3>stupid simple flask app<span class="date">7/6/2013</span></h3>
    <p>consider <a href="http://flask.pocoo.org">flask</a>, a delightful web application framework, commonly referred to as a micro framework.</p>
    <p>firing up a running web app in flask is cake.  import the Flask class, instantiate an application object from it, define a route and view function, and call <span class="inline code">run()</span> on your app object.</p>
    <pre class="code"><code>
    from flask import Flask, render_template

    app = Flask(__name__)

    @app.route('/')
    def index():
        return render_template('index.html')

    if __name__ == '__main__':
        app.run()
    </code></pre>
    <p>
        easy peasy.  this will serve the template called <span class="inline code">
            index.html</span> at the root ('<span class="inline code">/</span>') of the domain where the app is hanging out.
    </p>
</article>
<article>
    <h3>fab fun times<span class="date">7/6/2013</span></h3>
    <p>so as i continue on my magical journey to production quality 
    <a href="http://flask.pocoo.org">flask</a>, i discover my deep desire 
    for a not dumb deployment solution.  hence, 
    <a href="http://docs.fabfile.org/en/1.6/">fabric</a>.</p>

    <p>working with fabric, after some intial hiccups,  is actually pretty 
    delightful. it's a library created to facilitate interaction with remote 
    systems via ssh.  it picks up your <span class="inline code">.ssh/config</span> 
    and uses it right out of the box, and comes equipped with a simple 
    vocabulary for moving around the filesystem and working with files.</p>

        <p>i intend to use this lib quite a bit, so more in depth accounts of my experience doing so will follow.</p>
</article>
<article>
    <h3>hike night:  a hike at night<span class="date">7/5/2013</span></h3>
    <p> night one was a success.  i've reconsidered posting the route.  invite only.</p>
    <p> we found a delightful little creek with some absolutely quaint industrial rubble. i was enchanted by the host of spider webs.  walking a few yards up the creek,
    i found that i couldn't take three steps without almost creaming some little spiders pad.</p>
    <p> against established expectations,  clarksville has some nice little spots.  you just have to dig. </p>
</article>
<article>
    <h3> night hike: the setup <span class="date">7/1/2013</span></h3>
    <p> 
       this 4th of july we'll be engaging in the first night hike.  should be fun.  i'll post the route below.  for extra pop,  we'll be encouraging participants to bring along their favorite fireworks. 
    </p>
</article>

<article>
    <h3> welcome to the hive mind,  nerdhaus central <span class="date">7/1/2013</span></h3>
    <p>
        a log of the activities of the haus.  see this domain for tech, culture, and a running commentary of our work and escapades.  
    </p>

    <p> also note that the blog is open for submissions.  </p>

</article>

{% endblock %}

nerdhaus/templates/pages/cameron.html
{% extends "layout.html" %}
{% block body %}
<h2> Cameron </h2>
{% endblock %}

nerdhaus/templates/pages/cj.html
{% extends "layout.html" %}
{% block body %}
<h2> CJ </h2>
{% endblock %}

nerdhaus/templates/pages/ean.html
{% extends "layout.html" %}
{% block body %}
<h2> Ean </h2>
{% endblock %}

nerdhaus/templates/shows/index.html
{% extends "layouts/layout.html" %}
{% block title %}Haus Shows{% endblock %}
{% block body %}
<h1> SHOWS </h1>
{% endblock %}